#pragma once


#define MAPSIZE_X 12
#define MAPSIZE_Y 9
#define MAXIMUMPLAYERS 4
#define SMALLARROWTIME 2
#define SMALLARROWMULTIPLIER 0.6f
#define SMALLPUPMULTIPLIER 0.6f
#define MAXIMUMARROWS 6
#define NUMCARDINALDIRECTIONS 4
#define PUPSPEED 7.0f
#define RORIESPEED 5.7f
#define DEFAULTMINSPAWNTIME 0.01f
#define DEFAULTMAXSPAWNTIME 0.4f





